// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1280","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRD_FullscreenToggleOption","status":true,"description":"Adds a Fullscreen Toggle to the Options Window","parameters":{"Option Name":"Fullscreen","Position":"Middle","Default Value":"true","Persist Default?":"true"}},
{"name":"sair","status":true,"description":"Permite que o jogo seja encerrado","parameters":{"ShutDownName":"Sair\r"}},
{"name":"ShiftActors","status":true,"description":"Lets you shift SV actors with notetags.","parameters":{"Default Shift X":"300","Default Shift Y":"80"}},
{"name":"ShiftEnemies","status":true,"description":"v1.1.0 Lets you shift enemy battlers outside the boundaries of the Troop Window with notetags.","parameters":{"Default Shift X":"0","Default Shift Y":"80"}}
];
